name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-18.04]
        python-version: [3.7,3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up {{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      #        pip install .[dev]
      #        python install_dev.py
    - name: Test with pytest + Coverage
      run: |
        pytest --html=html/${{runs-on}}-test-results-${{ matrix.python-version }}.html
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: html/test-results-${{ matrix.python-version }}.html
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
