name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install .[dev]; fi
    - name: Test with pytest + Coverage
      run: |
        pytest --cov=./

    - name: Monitor coverage
      uses: slavcodev/coverage-monitor-action@1.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        clover_file: "logs/clover.xml"
        threshold_alert: 10
        threshold_warning: 50
